In [363]:
import numpy as np
import pandas as pd

In [364]:
df=pd.read_excel('Real estate valuation data set.xlsx')
df.head()

,No,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
0,1,2012.916667,32.0,84.87882,10,24.98298,121.54024,37.9
1,2,2012.916667,19.5,306.59470,9,24.98034,121.53951,42.2
2,3,2013.583333,13.3,561.98450,5,24.98746,121.54391,47.3
3,4,2013.500000,13.3,561.98450,5,24.98746,121.54391,54.8
4,5,2012.833333,5.0,390.56840,5,24.97937,121.54245,43.1

In [365]:
df1=df.iloc[1:,1:] #removing first row and first column as they where not useful
df1.head()

,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
1,2012.916667,19.5,306.5947,9,24.98034,121.53951,42.2
2,2013.583333,13.3,561.9845,5,24.98746,121.54391,47.3
3,2013.500000,13.3,561.9845,5,24.98746,121.54391,54.8
4,2012.833333,5.0,390.5684,5,24.97937,121.54245,43.1
5,2012.666667,7.1,2175.0300,3,24.96305,121.51254,32.1

In [366]:
y=df1.iloc[:,-1]
y.head()

1    42.2
2    47.3
3    54.8
4    43.1
5    32.1
Name: Y house price of unit area, dtype: float64

In [367]:
X=df1.iloc[:,:-1]
X.head()

,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude
1,2012.916667,19.5,306.5947,9,24.98034,121.53951
2,2013.583333,13.3,561.9845,5,24.98746,121.54391
3,2013.500000,13.3,561.9845,5,24.98746,121.54391
4,2012.833333,5.0,390.5684,5,24.97937,121.54245
5,2012.666667,7.1,2175.0300,3,24.96305,121.51254

In [368]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    train_size=0.80, 
                                                    random_state=42)

In [369]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(330, 6)
(330,)
(83, 6)
(83,)

In [370]:
import numpy as np
from sklearn.linear_model import LinearRegression

reg = LinearRegression().fit(X_train, y_train)
reg.score(X_train, y_train)

0.5712023634896385

In [371]:
print(reg.coef_)
print('')

[ 5.24973631e+00 -2.33729957e-01 -4.52091788e-03  1.16468684e+00
  2.15652006e+02 -3.12131568e+01]

In [372]:
print(reg.intercept_)

-12117.585888778862

In [373]:
y_pred=reg.predict(X_test)
y_pred

array([39.17775325, 40.86586446, 32.99721513, 31.53239473, 33.90831708,
       14.65457415, 34.20535526, 44.98531293, 37.17017321, 37.26638946,
       39.02638292, 35.35729893, 44.15149532, 43.81933491, 41.63837559,
       51.03241268, 45.34040118, 44.9262958 , 50.62921164, 40.18552364,
       48.50820728, 33.90189439, 38.94538452, 34.1757354 , 44.36745269,
       45.02309621, 43.52844756, 30.92422571, 35.57949699, 13.57364692,
       40.70766618, 37.90915218, 39.66236493, 27.68059614, 46.61356373,
       40.98275552, 50.41058957, 34.10591048, 43.11877704, 40.83904343,
       49.75425541, 49.16827448, 47.6628409 , 48.04688949, 39.60017638,
       30.93941611, 35.75172565, 13.16933587, 52.19139694, 48.04688949,
       37.35252605, 37.93453998, 41.93172214, 27.90492157, 43.63516509,
       15.50615738, 40.30957814, 28.00233664, 28.66597945, 14.67794714,
       50.06419238, 45.14815445, 39.42371896, 45.75243589, 47.56686511,
       47.2541008 , 37.8886751 , 33.26552173, 25.17353245, 47.41837014,
       47.06286786, 14.55010264, 47.09469249, 32.3874804 , 46.52745803,
       39.85947514, 40.21333492, 31.02590065, 47.75022957, 44.14110825,
       42.92181774, 46.73988974, 45.26578091])

In [374]:
y_test

395    42.5
350    42.3
401    27.7
354    30.1
182    23.6
       ...
288    51.0
323    42.5
203    46.1
275    49.7
390    38.6
Name: Y house price of unit area, Length: 83, dtype: float64

In [379]:
# def mean_square_error(y_p,y_t):
#     mse=0
#     for i in range(len(y_pred)):
#         mse=mse+(y_p[i]-y_t[i])*(y_p[i]-y_t[i])
#     return mse

from sklearn.metrics import mean_squared_error
mean_squared_error(y_pred,y_test)

70.60754022810056

In [380]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.6160276067509558

In [381]:
split=[0.6,0.7,0.8,0.9]
Split_Percent=[]
Score=[]
Coef=[]
Intercept=[]
MSE=[]
R2_score=[]

In [382]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression
for i in range(len(split)):
    X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=split[i], random_state=42)
    reg = LinearRegression().fit(X_train, y_train)
    print(split[i]*100,':',100-split[i]*100)
    a=split[i]*100
    b=100-split[i]*100
    Split_Percent.append(str(a)+'-'+str(b))
    print('score:',reg.score(X_train, y_train))
    Score.append(reg.score(X_train, y_train))
    print('coef:',reg.coef_)
    Coef.append((reg.coef_).tolist())
    print('intercept: ',reg.intercept_)
    Intercept.append(reg.intercept_)
    y_pred=reg.predict(X_test)
    print('mse: ',mean_squared_error(y_pred,y_test))
    MSE.append(mean_squared_error(y_pred,y_test))
    print(r2_score(y_test,y_pred))
    R2_score.append(r2_score(y_test,y_pred))
    print('')

60.0 : 40.0
score: 0.5572544618052881
coef: [ 5.72845254e+00 -2.41690048e-01 -4.65702338e-03  1.14537220e+00
  2.20627753e+02 -2.64101823e+01]
intercept:  -13788.72085448291
mse:  59.182213033936
0.6302473576637866

70.0 : 30.0
score: 0.5576607688271328
coef: [ 5.22371322e+00 -2.29270717e-01 -4.52464805e-03  1.10711776e+00
  2.35405761e+02 -2.69973228e+01]
intercept:  -13070.67562601684
mse:  60.95025985502265
0.6420809583941125

80.0 : 20.0
score: 0.5712023634896385
coef: [ 5.24973631e+00 -2.33729957e-01 -4.52091788e-03  1.16468684e+00
  2.15652006e+02 -3.12131568e+01]
intercept:  -12117.585888778862
mse:  70.60754022810056
0.6160276067509558

90.0 : 10.0
score: 0.5819675137204642
coef: [ 5.40384222e+00 -2.57570571e-01 -4.37793977e-03  1.12272040e+00
  2.30006072e+02 -1.85815541e+01]
intercept:  -14320.86492400202
mse:  77.2364772695931
0.5793411512792754

In [383]:
Coef_arr=np.array(Coef)

df = pd.DataFrame(list(zip(Split_Percent,Score,Intercept,Coef_arr[:,0],Coef_arr[:,1],Coef_arr[:,2],Coef_arr[:,3],Coef_arr[:,4],Coef_arr[:,5],MSE,R2_score )),
               columns =['Split_Percent','Score','Intercept','coef_1','coef_2','coef_3','coef_4','coef_5','coef_6','MSE','R2_score'])
df
# split=[0.6,0.7,0.8,0.9]
# Split_Percent=[]
# Score=[]
# Coef=[]
# Intercept=[]
# MSE=[]
# R2_score=[]

,Split_Percent,Score,Intercept,coef_1,coef_2,coef_3,coef_4,coef_5,coef_6,MSE,R2_score
0,60.0-40.0,0.557254,-13788.720854,5.728453,-0.241690,-0.004657,1.145372,220.627753,-26.410182,59.182213,0.630247
1,70.0-30.0,0.557661,-13070.675626,5.223713,-0.229271,-0.004525,1.107118,235.405761,-26.997323,60.950260,0.642081
2,80.0-20.0,0.571202,-12117.585889,5.249736,-0.233730,-0.004521,1.164687,215.652006,-31.213157,70.607540,0.616028
3,90.0-10.0,0.581968,-14320.864924,5.403842,-0.257571,-0.004378,1.122720,230.006072,-18.581554,77.236477,0.579341

In [384]:
lambd=[0.001,0.005,0.01,0.05,0.1,0.5]

In [385]:
split=[0.6,0.7,0.8,0.9]
Split_Percent=[]
Score=[]
Coef=[]
Intercept=[]
MSE=[]
R2_score=[]
Lambda=[]

In [386]:
from sklearn.linear_model import Ridge
for i in range(len(split)):
    for j in range(len(lambd)):
        X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=split[i], random_state=42)
        clf=Ridge(alpha=lambd[j])
        Lambda.append(lambd[j])
        clf.fit(X_train, y_train)
        print(split[i]*100,':',100-split[i]*100)
        a=split[i]*100
        b=100-split[i]*100
        Split_Percent.append(str(a)+'-'+str(b))
        print('score:',clf.score(X_train, y_train))
        Score.append(clf.score(X_train, y_train))
        print('coef:',clf.coef_)
        Coef.append((clf.coef_).tolist())
        print('intercept: ',clf.intercept_)
        Intercept.append(clf.intercept_)
        y_pred=clf.predict(X_test)
        # print(y_pred)
        print('mse: ',mean_squared_error(y_pred,y_test))
        MSE.append(mean_squared_error(y_pred,y_test))
        print('r2_score:',r2_score(y_test,y_pred))
        R2_score.append(r2_score(y_test,y_pred))
        print('')   

Coef_arr=np.array(Coef)

df1 = pd.DataFrame(list(zip(Split_Percent,Lambda,Score,Intercept,Coef_arr[:,0],Coef_arr[:,1],Coef_arr[:,2],Coef_arr[:,3],Coef_arr[:,4],Coef_arr[:,5],MSE,R2_score )),
               columns =['Split_Percent','Lambda','Score','Intercept','coef_1','coef_2','coef_3','coef_4','coef_5','coef_6','MSE','R2_score'])
df1

60.0 : 40.0
score: 0.5572202179173483
coef: [ 5.77129529e+00 -2.41553523e-01 -4.69235111e-03  1.14932908e+00
  2.12636621e+02 -2.60837414e+01]
intercept:  -13715.089992684158
mse:  59.20222288569581
r2_score: 0.6301223421366263

60.0 : 40.0
score: 0.5566005593683332
coef: [ 5.91606679e+00 -2.41079123e-01 -4.80719842e-03  1.16272336e+00
  1.85758795e+02 -2.45839020e+01]
intercept:  -13517.633614415874
mse:  59.348529490455114
r2_score: 0.6292082625352101

60.0 : 40.0
score: 0.5553012422431876
coef: [ 6.05315583e+00 -2.40611719e-01 -4.91001287e-03  1.17545244e+00
  1.60448661e+02 -2.26325021e+01]
intercept:  -13398.745462858042
mse:  59.59891129095677
r2_score: 0.6276439524565164

60.0 : 40.0
score: 0.5460028582811483
coef: [ 6.50465648e+00 -2.38929418e-01 -5.21654592e-03  1.21825348e+00
  7.68816420e+01 -1.28663204e+01]
intercept:  -13407.857710613227
mse:  61.218708194505744
r2_score: 0.6175239492590723

60.0 : 40.0
score: 0.5407041300083353
coef: [ 6.65784792e+00 -2.38252710e-01 -5.31642728e-03  1.23412556e+00
  4.65966507e+01 -8.20406819e+00]
intercept:  -13526.64555825707
mse:  62.10919152994011
r2_score: 0.611960477578072

60.0 : 40.0
score: 0.5331894813855929
coef: [ 6.71653825e+00 -2.37195733e-01 -5.42544667e-03  1.25398452e+00
  1.12509688e+01 -2.09491192e+00]
intercept:  -13504.684476120327
mse:  63.306409870443396
r2_score: 0.6044806179688913

70.0 : 30.0
score: 0.557630132368419
coef: [ 5.25443455e+00 -2.29222259e-01 -4.55874172e-03  1.11150782e+00
  2.28005567e+02 -2.68684253e+01]
intercept:  -12963.39270754852
mse:  60.89060184788481
r2_score: 0.6424312889224758

70.0 : 30.0
score: 0.5570558899195717
coef: [ 5.36043306e+00 -2.29037958e-01 -4.67165937e-03  1.12668363e+00
  2.02576009e+02 -2.60001978e+01]
intercept:  -12647.289950131097
mse:  60.747589451651464
r2_score: 0.6432711025659181

70.0 : 30.0
score: 0.5557948689308356
coef: [ 5.46406769e+00 -2.28833492e-01 -4.77553309e-03  1.14157475e+00
  1.77837269e+02 -2.45561425e+01]
intercept:  -12413.668785946942
mse:  60.701819122159726
r2_score: 0.6435398802955723

70.0 : 30.0
score: 0.5456377607055214
coef: [ 5.83096634e+00 -2.27927261e-01 -5.10193506e-03  1.19529005e+00
  9.01271736e+01 -1.52402904e+01]
intercept:  -12094.310241630465
mse:  61.30345127383705
r2_score: 0.6400069076119475

70.0 : 30.0
score: 0.5391990289692978
coef: [ 5.96695090e+00 -2.27496281e-01 -5.21408952e-03  1.21670125e+00
  5.57990708e+01 -1.00392977e+01]
intercept:  -12142.99045875102
mse:  61.87147354040162
r2_score: 0.6366713027147217

70.0 : 30.0
score: 0.5293921381334944
coef: [ 6.04039657e+00 -2.26810884e-01 -5.34016782e-03  1.24370017e+00
  1.38101298e+01 -2.65733915e+00]
intercept:  -12139.556365431574
mse:  62.80454564151418
r2_score: 0.6311920106990063

80.0 : 20.0
score: 0.5711813461288751
coef: [ 5.27291759e+00 -2.33526763e-01 -4.54672758e-03  1.16860747e+00
  2.09589495e+02 -3.09338935e+01]
intercept:  -12046.80985849274
mse:  70.65638751147371
r2_score: 0.6157619692816443

80.0 : 20.0
score: 0.5707772289581248
coef: [ 5.35383750e+00 -2.32805891e-01 -4.63337664e-03  1.18242740e+00
  1.88435373e+02 -2.96311584e+01]
intercept:  -11839.817438729708
mse:  70.86376040854464
r2_score: 0.6146342502402207

80.0 : 20.0
score: 0.5698593259820802
coef: [ 5.43441545e+00 -2.32070488e-01 -4.71467445e-03  1.19639677e+00
  1.67366522e+02 -2.78521712e+01]
intercept:  -11692.15303422791
mse:  71.12833302268783
r2_score: 0.6131954721789467

80.0 : 20.0
score: 0.5617621180627197
coef: [ 5.73266257e+00 -2.29180460e-01 -4.97994643e-03  1.25029291e+00
  8.85186059e+01 -1.74479458e+01]
intercept:  -11588.26017106065
mse:  72.65297900017438
r2_score: 0.6049042618784346

80.0 : 20.0
score: 0.5561854447578678
coef: [ 5.84936232e+00 -2.27920267e-01 -5.07438019e-03  1.27337462e+00
  5.57594716e+01 -1.16184920e+01]
intercept:  -11713.718994539202
mse:  73.54300907034224
r2_score: 0.6000641700836782

80.0 : 20.0
score: 0.5471672754756114
coef: [ 5.91993249e+00 -2.26225233e-01 -5.18185870e-03  1.30369797e+00
  1.41008496e+01 -3.12329909e+00]
intercept:  -11848.098845551007
mse:  74.87867665309847
r2_score: 0.5928006472831493

90.0 : 10.0
score: 0.5819477405657758
coef: [ 5.42160905e+00 -2.57308658e-01 -4.41065048e-03  1.12610032e+00
  2.23938227e+02 -1.88051332e+01]
intercept:  -14177.93364112406
mse:  77.19143292065237
r2_score: 0.5795864797126351

90.0 : 10.0
score: 0.5815631812212316
coef: [ 5.48391652e+00 -2.56371355e-01 -4.52201294e-03  1.13810874e+00
  2.02599358e+02 -1.92334604e+01]
intercept:  -13718.442331386088
mse:  77.0719209739452
r2_score: 0.5802373866375423

90.0 : 10.0
score: 0.5806759403626205
coef: [ 5.54642331e+00 -2.55401685e-01 -4.62871162e-03  1.15040149e+00
  1.81085544e+02 -1.91217348e+01]
intercept:  -13320.6253098849
mse:  77.01322487264784
r2_score: 0.5805570676389163

90.0 : 10.0
score: 0.5724769208474552
coef: [ 5.78218444e+00 -2.51451261e-01 -4.99251637e-03  1.19939655e+00
  9.81406570e+01 -1.40594656e+01]
intercept:  -12339.291279423007
mse:  77.38002517462441
r2_score: 0.5785593355025671

90.0 : 10.0
score: 0.5665672132125515
coef: [ 5.87639245e+00 -2.49657136e-01 -5.12812296e-03  1.22119491e+00
  6.24754761e+01 -9.86349274e+00]
intercept:  -12148.339982341759
mse:  77.8326878989948
r2_score: 0.5760939643822893

90.0 : 10.0
score: 0.5566561789973087
coef: [ 5.93099559e+00 -2.47205138e-01 -5.28729888e-03  1.25058587e+00
  1.60134660e+01 -2.81008246e+00]
intercept:  -11955.360684852021
mse:  78.66152383119173
r2_score: 0.5715798127619436

,Split_Percent,Lambda,Score,Intercept,coef_1,coef_2,coef_3,coef_4,coef_5,coef_6,MSE,R2_score
0,60.0-40.0,0.001,0.557220,-13715.089993,5.771295,-0.241554,-0.004692,1.149329,212.636621,-26.083741,59.202223,0.630122
1,60.0-40.0,0.005,0.556601,-13517.633614,5.916067,-0.241079,-0.004807,1.162723,185.758795,-24.583902,59.348529,0.629208
2,60.0-40.0,0.010,0.555301,-13398.745463,6.053156,-0.240612,-0.004910,1.175452,160.448661,-22.632502,59.598911,0.627644
3,60.0-40.0,0.050,0.546003,-13407.857711,6.504656,-0.238929,-0.005217,1.218253,76.881642,-12.866320,61.218708,0.617524
4,60.0-40.0,0.100,0.540704,-13526.645558,6.657848,-0.238253,-0.005316,1.234126,46.596651,-8.204068,62.109192,0.611960
5,60.0-40.0,0.500,0.533189,-13504.684476,6.716538,-0.237196,-0.005425,1.253985,11.250969,-2.094912,63.306410,0.604481
6,70.0-30.0,0.001,0.557630,-12963.392708,5.254435,-0.229222,-0.004559,1.111508,228.005567,-26.868425,60.890602,0.642431
7,70.0-30.0,0.005,0.557056,-12647.289950,5.360433,-0.229038,-0.004672,1.126684,202.576009,-26.000198,60.747589,0.643271
8,70.0-30.0,0.010,0.555795,-12413.668786,5.464068,-0.228833,-0.004776,1.141575,177.837269,-24.556142,60.701819,0.643540
9,70.0-30.0,0.050,0.545638,-12094.310242,5.830966,-0.227927,-0.005102,1.195290,90.127174,-15.240290,61.303451,0.640007
10,70.0-30.0,0.100,0.539199,-12142.990459,5.966951,-0.227496,-0.005214,1.216701,55.799071,-10.039298,61.871474,0.636671
11,70.0-30.0,0.500,0.529392,-12139.556365,6.040397,-0.226811,-0.005340,1.243700,13.810130,-2.657339,62.804546,0.631192
12,80.0-20.0,0.001,0.571181,-12046.809858,5.272918,-0.233527,-0.004547,1.168607,209.589495,-30.933893,70.656388,0.615762
13,80.0-20.0,0.005,0.570777,-11839.817439,5.353837,-0.232806,-0.004633,1.182427,188.435373,-29.631158,70.863760,0.614634
14,80.0-20.0,0.010,0.569859,-11692.153034,5.434415,-0.232070,-0.004715,1.196397,167.366522,-27.852171,71.128333,0.613195
15,80.0-20.0,0.050,0.561762,-11588.260171,5.732663,-0.229180,-0.004980,1.250293,88.518606,-17.447946,72.652979,0.604904
16,80.0-20.0,0.100,0.556185,-11713.718995,5.849362,-0.227920,-0.005074,1.273375,55.759472,-11.618492,73.543009,0.600064
17,80.0-20.0,0.500,0.547167,-11848.098846,5.919932,-0.226225,-0.005182,1.303698,14.100850,-3.123299,74.878677,0.592801
18,90.0-10.0,0.001,0.581948,-14177.933641,5.421609,-0.257309,-0.004411,1.126100,223.938227,-18.805133,77.191433,0.579586
19,90.0-10.0,0.005,0.581563,-13718.442331,5.483917,-0.256371,-0.004522,1.138109,202.599358,-19.233460,77.071921,0.580237
20,90.0-10.0,0.010,0.580676,-13320.625310,5.546423,-0.255402,-0.004629,1.150401,181.085544,-19.121735,77.013225,0.580557
21,90.0-10.0,0.050,0.572477,-12339.291279,5.782184,-0.251451,-0.004993,1.199397,98.140657,-14.059466,77.380025,0.578559
22,90.0-10.0,0.100,0.566567,-12148.339982,5.876392,-0.249657,-0.005128,1.221195,62.475476,-9.863493,77.832688,0.576094
23,90.0-10.0,0.500,0.556656,-11955.360685,5.930996,-0.247205,-0.005287,1.250586,16.013466,-2.810082,78.661524,0.571580

In [387]:
df1 # ridge regression

,Split_Percent,Lambda,Score,Intercept,coef_1,coef_2,coef_3,coef_4,coef_5,coef_6,MSE,R2_score
0,60.0-40.0,0.001,0.557220,-13715.089993,5.771295,-0.241554,-0.004692,1.149329,212.636621,-26.083741,59.202223,0.630122
1,60.0-40.0,0.005,0.556601,-13517.633614,5.916067,-0.241079,-0.004807,1.162723,185.758795,-24.583902,59.348529,0.629208
2,60.0-40.0,0.010,0.555301,-13398.745463,6.053156,-0.240612,-0.004910,1.175452,160.448661,-22.632502,59.598911,0.627644
3,60.0-40.0,0.050,0.546003,-13407.857711,6.504656,-0.238929,-0.005217,1.218253,76.881642,-12.866320,61.218708,0.617524
4,60.0-40.0,0.100,0.540704,-13526.645558,6.657848,-0.238253,-0.005316,1.234126,46.596651,-8.204068,62.109192,0.611960
5,60.0-40.0,0.500,0.533189,-13504.684476,6.716538,-0.237196,-0.005425,1.253985,11.250969,-2.094912,63.306410,0.604481
6,70.0-30.0,0.001,0.557630,-12963.392708,5.254435,-0.229222,-0.004559,1.111508,228.005567,-26.868425,60.890602,0.642431
7,70.0-30.0,0.005,0.557056,-12647.289950,5.360433,-0.229038,-0.004672,1.126684,202.576009,-26.000198,60.747589,0.643271
8,70.0-30.0,0.010,0.555795,-12413.668786,5.464068,-0.228833,-0.004776,1.141575,177.837269,-24.556142,60.701819,0.643540
9,70.0-30.0,0.050,0.545638,-12094.310242,5.830966,-0.227927,-0.005102,1.195290,90.127174,-15.240290,61.303451,0.640007
10,70.0-30.0,0.100,0.539199,-12142.990459,5.966951,-0.227496,-0.005214,1.216701,55.799071,-10.039298,61.871474,0.636671
11,70.0-30.0,0.500,0.529392,-12139.556365,6.040397,-0.226811,-0.005340,1.243700,13.810130,-2.657339,62.804546,0.631192
12,80.0-20.0,0.001,0.571181,-12046.809858,5.272918,-0.233527,-0.004547,1.168607,209.589495,-30.933893,70.656388,0.615762
13,80.0-20.0,0.005,0.570777,-11839.817439,5.353837,-0.232806,-0.004633,1.182427,188.435373,-29.631158,70.863760,0.614634
14,80.0-20.0,0.010,0.569859,-11692.153034,5.434415,-0.232070,-0.004715,1.196397,167.366522,-27.852171,71.128333,0.613195
15,80.0-20.0,0.050,0.561762,-11588.260171,5.732663,-0.229180,-0.004980,1.250293,88.518606,-17.447946,72.652979,0.604904
16,80.0-20.0,0.100,0.556185,-11713.718995,5.849362,-0.227920,-0.005074,1.273375,55.759472,-11.618492,73.543009,0.600064
17,80.0-20.0,0.500,0.547167,-11848.098846,5.919932,-0.226225,-0.005182,1.303698,14.100850,-3.123299,74.878677,0.592801
18,90.0-10.0,0.001,0.581948,-14177.933641,5.421609,-0.257309,-0.004411,1.126100,223.938227,-18.805133,77.191433,0.579586
19,90.0-10.0,0.005,0.581563,-13718.442331,5.483917,-0.256371,-0.004522,1.138109,202.599358,-19.233460,77.071921,0.580237
20,90.0-10.0,0.010,0.580676,-13320.625310,5.546423,-0.255402,-0.004629,1.150401,181.085544,-19.121735,77.013225,0.580557
21,90.0-10.0,0.050,0.572477,-12339.291279,5.782184,-0.251451,-0.004993,1.199397,98.140657,-14.059466,77.380025,0.578559
22,90.0-10.0,0.100,0.566567,-12148.339982,5.876392,-0.249657,-0.005128,1.221195,62.475476,-9.863493,77.832688,0.576094
23,90.0-10.0,0.500,0.556656,-11955.360685,5.930996,-0.247205,-0.005287,1.250586,16.013466,-2.810082,78.661524,0.571580

In [388]:
split=[0.6,0.7,0.8,0.9]
Split_Percent=[]
Score=[]
Coef=[]
Intercept=[]
MSE=[]
R2_score=[]
Lambda=[]

In [389]:
from sklearn import linear_model
for i in range(len(split)):
    for j in range(len(lambd)):
        X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=split[i], random_state=42)
        clf = linear_model.Lasso(alpha=lambd[j])
        Lambda.append(lambd[j])
        clf.fit(X_train, y_train)
        print(split[i]*100,':',100-split[i]*100)
        a=split[i]*100
        b=100-split[i]*100
        Split_Percent.append(str(a)+'-'+str(b))
        print('score:',clf.score(X_train, y_train))
        Score.append(clf.score(X_train, y_train))
        print('coef:',clf.coef_)
        Coef.append((clf.coef_).tolist())
        print('intercept: ',clf.intercept_)
        Intercept.append(clf.intercept_)
        y_pred=clf.predict(X_test)
        # print(y_pred)
        print('mse: ',mean_squared_error(y_pred,y_test))
        MSE.append(mean_squared_error(y_pred,y_test))
        print('r2_score:',r2_score(y_test,y_pred))
        R2_score.append(r2_score(y_test,y_pred))
        print('')

60.0 : 40.0
score: 0.5571635993860775
coef: [ 5.78251388e+00 -2.41155773e-01 -4.59845783e-03  1.15149676e+00
  2.12248200e+02 -1.63875473e+01]
intercept:  -14906.504758162817
mse:  59.16580511189934
r2_score: 0.630349869418878

60.0 : 40.0
score: 0.5557986054037175
coef: [ 5.95648934e+00 -2.39855720e-01 -4.60867821e-03  1.17210645e+00
  1.76639616e+02 -0.00000000e+00]
intercept:  -16359.348937673396
mse:  59.37751890215706
r2_score: 0.6290271454220258

60.0 : 40.0
score: 0.5523720520909732
coef: [ 6.13742752e+00 -2.38954013e-01 -4.83274496e-03  1.19450791e+00
  1.30322253e+02 -0.00000000e+00]
intercept:  -15566.952987478575
mse:  60.008126310152456
r2_score: 0.6250873002653503

60.0 : 40.0
score: 0.5303505690958638
coef: [ 6.30997842e+00 -2.35465037e-01 -5.46624817e-03  1.25688151e+00
  0.00000000e+00 -0.00000000e+00]
intercept:  -12659.881263914354
mse:  63.56922438795038
r2_score: 0.6028386320188763

60.0 : 40.0
score: 0.5298660876184773
coef: [ 5.66105287e+00 -2.33630013e-01 -5.47211631e-03  1.25561869e+00
  0.00000000e+00 -0.00000000e+00]
intercept:  -11353.50715023798
mse:  63.374300998163115
r2_score: 0.6040564546505789

60.0 : 40.0
score: 0.5143626640072897
coef: [ 0.46947237 -0.21896202 -0.00551847  1.24567641  0.         -0.        ]
intercept:  -902.1608919748826
mse:  64.41807796658989
r2_score: 0.5975352505201389

70.0 : 30.0
score: 0.5575635390548479
coef: [ 5.25928833e+00 -2.28768759e-01 -4.46144355e-03  1.11409909e+00
  2.27122786e+02 -1.66729653e+01]
intercept:  -14190.333922729787
mse:  60.809397274872005
r2_score: 0.6429081476432736

70.0 : 30.0
score: 0.5561092345351797
coef: [ 5.37802795e+00 -2.27764311e-01 -4.46620755e-03  1.13837115e+00
  1.91438656e+02 -0.00000000e+00]
intercept:  -15564.803327809615
mse:  60.57590842764404
r2_score: 0.6442792673829478

70.0 : 30.0
score: 0.5524476506441102
coef: [ 5.50651209e+00 -2.27357979e-01 -4.69017695e-03  1.16561916e+00
  1.44673258e+02 -0.00000000e+00]
intercept:  -14655.642405489454
mse:  60.68393327780294
r2_score: 0.6436449115831455

70.0 : 30.0
score: 0.525534539313242
coef: [ 5.57991273e+00 -2.25434618e-01 -5.38496354e-03  1.24835980e+00
  0.00000000e+00 -0.00000000e+00]
intercept:  -11190.647055010484
mse:  63.081535875995044
r2_score: 0.6295654371701092

70.0 : 30.0
score: 0.5250120992420426
coef: [ 4.91938662 -0.22407679 -0.00538885  1.24519662  0.         -0.        ]
intercept:  -9860.904555014427
mse:  63.01772373270934
r2_score: 0.6299401620887882

70.0 : 30.0
score: 0.5101376014432144
coef: [ 0.         -0.21363879 -0.0054247   1.21665522  0.         -0.        ]
intercept:  42.613008691735544
mse:  65.03230399283069
r2_score: 0.618109914971616

80.0 : 20.0
score: 0.5710999390219558
coef: [ 5.27400373e+00 -2.33065658e-01 -4.45127825e-03  1.17433750e+00
  2.07263414e+02 -2.06783425e+01]
intercept:  -13237.444298105196
mse:  70.54917885619513
r2_score: 0.6163449829911056

80.0 : 20.0
score: 0.5694656341033224
coef: [ 5.37008137e+00 -2.31102831e-01 -4.40669153e-03  1.20535550e+00
  1.71338219e+02 -0.00000000e+00]
intercept:  -15047.166594745682
mse:  70.77690210400313
r2_score: 0.6151065962667303

80.0 : 20.0
score: 0.5655930071126984
coef: [ 5.48898730e+00 -2.29485578e-01 -4.63276783e-03  1.23499264e+00
  1.23576049e+02 -0.00000000e+00]
intercept:  -14093.871292865108
mse:  71.6410852423359
r2_score: 0.610407063231602

80.0 : 20.0
score: 0.543453413112545
coef: [ 5.44852208e+00 -2.24778355e-01 -5.21706403e-03  1.30998596e+00
  0.00000000e+00 -0.00000000e+00]
intercept:  -10926.583666927563
mse:  75.25545407125384
r2_score: 0.5907516858478132

80.0 : 20.0
score: 0.5429270231020137
coef: [ 4.80537288 -0.22381247 -0.00521588  1.30687005  0.         -0.        ]
intercept:  -9631.82168495288
mse:  75.14668834197349
r2_score: 0.5913431671151161

80.0 : 20.0
score: 0.5278606974839495
coef: [ 0.         -0.21629649 -0.00521353  1.27873854  0.         -0.        ]
intercept:  42.18217558533313
mse:  76.62617627851128
r2_score: 0.5832975317348111

90.0 : 10.0
score: 0.5818625981028769
coef: [ 5.41493945e+00 -2.56679813e-01 -4.31276201e-03  1.13125244e+00
  2.21251306e+02 -7.94545489e+00]
intercept:  -15417.368848574155
mse:  77.0652288020063
r2_score: 0.5802738347180709

90.0 : 10.0
score: 0.5804641170520672
coef: [ 5.47814746e+00 -2.54501769e-01 -4.42670717e-03  1.15589706e+00
  1.82259619e+02 -0.00000000e+00]
intercept:  -15536.6787705799
mse:  76.82342475885754
r2_score: 0.5815907903069687

90.0 : 10.0
score: 0.5764209591100857
coef: [ 5.56256092e+00 -2.52176771e-01 -4.67668930e-03  1.18398042e+00
  1.32379571e+02 -0.00000000e+00]
intercept:  -14461.035312614666
mse:  76.92104705312185
r2_score: 0.5810591026463396

90.0 : 10.0
score: 0.5524871278824715
coef: [ 5.45104275e+00 -2.45523935e-01 -5.33971459e-03  1.25680547e+00
  0.00000000e+00 -0.00000000e+00]
intercept:  -10930.813018349609
mse:  78.77078778092806
r2_score: 0.5709847202754967

90.0 : 10.0
score: 0.5519738644763137
coef: [ 4.82325277 -0.24462475 -0.00533876  1.25366024  0.         -0.        ]
intercept:  -9666.976235248678
mse:  78.5059420017455
r2_score: 0.5724271698083853

90.0 : 10.0
score: 0.5365999070875109
coef: [ 0.         -0.2375399  -0.00533562  1.22651558  0.         -0.        ]
intercept:  42.97930397071673
mse:  78.50052982089267
r2_score: 0.572456646576968

In [392]:

Coef_arr=np.array(Coef)

df2 = pd.DataFrame(list(zip(Split_Percent,Lambda,Score,Intercept,Coef_arr[:,0],Coef_arr[:,1],Coef_arr[:,2],Coef_arr[:,3],Coef_arr[:,4],Coef_arr[:,5],MSE,R2_score )),
               columns =['Split_Percent','Lambda','Score','Intercept','coef_1','coef_2','coef_3','coef_4','coef_5','coef_6','MSE','R2_score'])
df2 # Lasso Regression

,Split_Percent,Lambda,Score,Intercept,coef_1,coef_2,coef_3,coef_4,coef_5,coef_6,MSE,R2_score
0,60.0-40.0,0.001,0.557164,-14906.504758,5.782514,-0.241156,-0.004598,1.151497,212.248200,-16.387547,59.165805,0.630350
1,60.0-40.0,0.005,0.555799,-16359.348938,5.956489,-0.239856,-0.004609,1.172106,176.639616,-0.000000,59.377519,0.629027
2,60.0-40.0,0.010,0.552372,-15566.952987,6.137428,-0.238954,-0.004833,1.194508,130.322253,-0.000000,60.008126,0.625087
3,60.0-40.0,0.050,0.530351,-12659.881264,6.309978,-0.235465,-0.005466,1.256882,0.000000,-0.000000,63.569224,0.602839
4,60.0-40.0,0.100,0.529866,-11353.507150,5.661053,-0.233630,-0.005472,1.255619,0.000000,-0.000000,63.374301,0.604056
5,60.0-40.0,0.500,0.514363,-902.160892,0.469472,-0.218962,-0.005518,1.245676,0.000000,-0.000000,64.418078,0.597535
6,70.0-30.0,0.001,0.557564,-14190.333923,5.259288,-0.228769,-0.004461,1.114099,227.122786,-16.672965,60.809397,0.642908
7,70.0-30.0,0.005,0.556109,-15564.803328,5.378028,-0.227764,-0.004466,1.138371,191.438656,-0.000000,60.575908,0.644279
8,70.0-30.0,0.010,0.552448,-14655.642405,5.506512,-0.227358,-0.004690,1.165619,144.673258,-0.000000,60.683933,0.643645
9,70.0-30.0,0.050,0.525535,-11190.647055,5.579913,-0.225435,-0.005385,1.248360,0.000000,-0.000000,63.081536,0.629565
10,70.0-30.0,0.100,0.525012,-9860.904555,4.919387,-0.224077,-0.005389,1.245197,0.000000,-0.000000,63.017724,0.629940
11,70.0-30.0,0.500,0.510138,42.613009,0.000000,-0.213639,-0.005425,1.216655,0.000000,-0.000000,65.032304,0.618110
12,80.0-20.0,0.001,0.571100,-13237.444298,5.274004,-0.233066,-0.004451,1.174337,207.263414,-20.678342,70.549179,0.616345
13,80.0-20.0,0.005,0.569466,-15047.166595,5.370081,-0.231103,-0.004407,1.205355,171.338219,-0.000000,70.776902,0.615107
14,80.0-20.0,0.010,0.565593,-14093.871293,5.488987,-0.229486,-0.004633,1.234993,123.576049,-0.000000,71.641085,0.610407
15,80.0-20.0,0.050,0.543453,-10926.583667,5.448522,-0.224778,-0.005217,1.309986,0.000000,-0.000000,75.255454,0.590752
16,80.0-20.0,0.100,0.542927,-9631.821685,4.805373,-0.223812,-0.005216,1.306870,0.000000,-0.000000,75.146688,0.591343
17,80.0-20.0,0.500,0.527861,42.182176,0.000000,-0.216296,-0.005214,1.278739,0.000000,-0.000000,76.626176,0.583298
18,90.0-10.0,0.001,0.581863,-15417.368849,5.414939,-0.256680,-0.004313,1.131252,221.251306,-7.945455,77.065229,0.580274
19,90.0-10.0,0.005,0.580464,-15536.678771,5.478147,-0.254502,-0.004427,1.155897,182.259619,-0.000000,76.823425,0.581591
20,90.0-10.0,0.010,0.576421,-14461.035313,5.562561,-0.252177,-0.004677,1.183980,132.379571,-0.000000,76.921047,0.581059
21,90.0-10.0,0.050,0.552487,-10930.813018,5.451043,-0.245524,-0.005340,1.256805,0.000000,-0.000000,78.770788,0.570985
22,90.0-10.0,0.100,0.551974,-9666.976235,4.823253,-0.244625,-0.005339,1.253660,0.000000,-0.000000,78.505942,0.572427
23,90.0-10.0,0.500,0.536600,42.979304,0.000000,-0.237540,-0.005336,1.226516,0.000000,-0.000000,78.500530,0.572457

In [393]:
data = pd.read_csv("haberman.data",sep=',')
data

     30  64   1  1.1
0    30  62   3    1
1    30  65   0    1
2    31  59   2    1
3    31  65   4    1
4    33  58  10    1
..   ..  ..  ..  ...
300  75  62   1    1
301  76  67   0    1
302  77  65   3    1
303  78  65   1    2
304  83  58   2    2

[305 rows x 4 columns]

In [394]:
feature=data.iloc[:,:3]
feature.head()

   30  64   1
0  30  62   3
1  30  65   0
2  31  59   2
3  31  65   4
4  33  58  10

In [395]:
label=data.iloc[:,-1]
label.head()

0    1
1    1
2    1
3    1
4    1
Name: 1.1, dtype: int64

In [396]:
X_train, X_test, y_train, y_test = train_test_split(feature,label, train_size=0.80, random_state=42)
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(244, 3)
(244,)
(61, 3)
(61,)

In [397]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state=42).fit(X_train, y_train)
y_pred=clf.predict(X_test)
print(y_pred.tolist())
print('score: ',clf.score(X_train, y_train))
print('coef: ',clf.coef_)
print('intercept: ', clf.intercept_)
print(y_test.tolist())

[1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1]
score:  0.7418032786885246
coef:  [[0.02812687 0.00398767 0.08518767]]
intercept:  [-3.0964907]
[2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1, 1, 1, 1, 1]

In [398]:
def log_reg_error(yp,yt):
    sum=0
    for i in range(len(yp)):
        if yp[i]!=yt[i]:
            sum+=1
    return sum/len(yp)

In [399]:
print('error: ',log_reg_error(y_pred.tolist(),y_test.tolist()))

error:  0.22950819672131148

In [400]:
split=[0.6,0.7,0.8,0.9]
Split_Percent=[]
Score=[]
Coef=[]
Intercept=[]
CE=[]

In [401]:
split=[0.6,0.7,0.8,0.9]
for i in range(len(split)):
    X_train, X_test, y_train, y_test = train_test_split(feature,label,train_size=split[i], random_state=42)
    clf = LogisticRegression(random_state=0).fit(X_train, y_train)
    clf.fit(X_train, y_train)
    print(split[i]*100,':',100-split[i]*100)
    a=split[i]*100
    b=100-split[i]*100
    Split_Percent.append(str(a)+'-'+str(b))
    print('score:',clf.score(X_train, y_train))
    Score.append(clf.score(X_train, y_train))
    print('coef:',clf.coef_)
    Coef.append((clf.coef_).tolist())
    print('intercept: ',clf.intercept_)
    Intercept.append(clf.intercept_)
    y_pred=clf.predict(X_test)
    # print(y_pred)
    print('classiication error: ',log_reg_error(y_pred.tolist(),y_test.tolist()))
    CE.append(log_reg_error(y_pred.tolist(),y_test.tolist()))
#     print('r2_score:',r2_score(y_test,y_pred))
#     R2_score.append(r2_score(y_test,y_pred))
    print('')

60.0 : 40.0
score: 0.7486338797814208
coef: [[ 0.04043536 -0.02055534  0.09466198]]
intercept:  [-2.31430971]
classiication error:  0.2540983606557377

70.0 : 30.0
score: 0.7511737089201878
coef: [[ 0.03567844 -0.01967363  0.09460609]]
intercept:  [-2.09708717]
classiication error:  0.25

80.0 : 20.0
score: 0.7418032786885246
coef: [[0.02812687 0.00398767 0.08518767]]
intercept:  [-3.0964907]
classiication error:  0.22950819672131148

90.0 : 10.0
score: 0.7445255474452555
coef: [[ 0.01853647 -0.00716571  0.08512009]]
intercept:  [-1.94058753]
classiication error:  0.25806451612903225

In [402]:
Coef_arr=np.array(Coef)

df3 = pd.DataFrame(list(zip(Split_Percent,Score,Intercept,Coef_arr[:,:,0],Coef_arr[:,:,1],Coef_arr[:,:,2],CE,R2_score )),columns =['Split_Percent','Score','Intercept','coef_1','coef_2','coef_3','Classification Error','R2_score'])
df3 # Logistic Regression

,Split_Percent,Score,Intercept,coef_1,coef_2,coef_3,Classification Error,R2_score
0,60.0-40.0,0.748634,[-2.3143097082493704],[0.04043535530525819],[-0.020555341838654744],[0.09466198077890109],0.254098,0.630350
1,70.0-30.0,0.751174,[-2.0970871724249442],[0.03567843516992887],[-0.019673629677562726],[0.09460608901385324],0.250000,0.629027
2,80.0-20.0,0.741803,[-3.096490701695725],[0.028126865564160095],[0.003987668691776347],[0.08518767486372819],0.229508,0.625087
3,90.0-10.0,0.744526,[-1.9405875254221727],[0.01853647085051108],[-0.007165711954915214],[0.08512008659952519],0.258065,0.602839